### ISSUE TITLE
CSS for all elements in custom CSS is stripped out of CSS output.

### ISSUE THREAD

**Issue by fuzzyweapon** [AresMUSH/ares-webportal#29]
I'm unfamiliar with Ember and the rest of the tech stack that the web portal uses, so bear with me.  I might just be doing things wrong, but it seems like the way the custom CSS section is generated will not allow for styling all selectors.  The biggest usage of this would be to use an import statement to pull in a font from something like https://fonts.google.com and style the entire website with that font.

which is what I'm trying to do via `Admin>Setup>Website>Custom CSS Style`:

```css
@import url("https://fonts.googleapis.com/css?family=Rajdhani");
/* Put any custom styles here.  They will override the default styles. */
* {
  font-family: 'Rajdhani', sans-serif;
}
```

produces this CSS (just an exerpt) in `ares.css`:

```css
@charset "UTF-8";
/* -------------------------
BASIC CONTAINERS
------------------------- */
@import url("https://fonts.googleapis.com/css?family=Rajdhani");
.container {
  background-color: #3d65a3;
  margin: 0;
  width: 100%;
  padding-left: 25px;
  padding-right: 25px; }
// ... rest is redacted for brevity
// And yet I didn't see the all selector (*) statement anywhere.
```
Should I be escaping the wildcard somehow?
